#!/usr/bin/env python3
"""
Pre-Commit hook checking for pep8 complience and pyflakes errors.
Pro Tip: Ignore errors with ``git commit -n``.
"""
import re
import subprocess
import sys


_MODIFIED_RE = re.compile('^(?:M|A)..(?P<name>.*\.py)', re.M)


def main():
    p = subprocess.Popen(['git', 'status', '--porcelain'],
                         stdout=subprocess.PIPE)
    out, err = p.communicate()
    modifieds = _MODIFIED_RE.findall(out.decode('utf-8'))

    rrcode = 0
    for file in modifieds:
        p = subprocess.Popen(
            ['pycodestyle', '--repeat', '--show-source', '--max-line-length=119', file],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        out, err = p.communicate()
        if out or err:
            print(
                f"pycodestyle:\n\t[OUT] {out.decode('utf-8')}\t[ERR] {err.decode('utf-8')}",
                file=sys.stdout
            )
            rrcode = rrcode | 1
        retcode = subprocess.call(['pyflakes', file])
        rrcode = retcode | rrcode

    sys.exit(rrcode)


if __name__ == '__main__':
    main()