#!/usr/bin/env python
#
# Copyright 2019 Volusion, LLC (http://www.volusion.com)
#
# Coded by Brad Bolander & Phil Manno, April 2019

####SALESFORCE####
SALESFORCE_USERNAME = 'REDACTED'
SALESFORCE_PASSWORD = 'REDACTED'
SALESFORCE_TOKEN = 'REDACTED'

# Redis
REDIS_HOST_URL = "REDACTED"
REDIS_PORT = REDACTED
REDIS_PASSWORD = "REDACTED"

# GCP
GCP_PROJECT = "REDACTED"
GCP_V1_QUEUE = "REDACTED"
GCP_V2_QUEUE = "REDACTED"
GCP_V2_UPDATE_QUEUE = "REDACTED"
GCP_LOCATION = "REDACTED"
GCP_CREDENTIALS = "REDACTED"